-- SQLBook: Code
-- Run this in the Supabase SQL Editor. Adds the RPC functions the Nurse
-- Dashboard needs for patients, discharge_requests, and tasks. These tables
-- have RLS enabled with no policies (same as officers/credentials), so the
-- only way in is through these SECURITY DEFINER functions, mirroring
-- login_administrator.
--
-- Ownership is enforced by comparing p_officer_id against the row's
-- officer_id/requested_by/assigned_to column, NOT by auth.uid() — this app
-- has no real Supabase Auth session, so the officer id is whatever the
-- client passes in from its own cookie session. Trust boundary is the same
-- as login_administrator's.

-- ── tables (create if missing) ────────────────────────────────────────
-- discharge_requests and tasks were only ever in the ERD, never actually
-- created in the database — that's why create_discharge_request and the
-- list_tasks_by_officer/list_discharge_requests_by_officer functions fail
-- with "relation ... does not exist". Creating them here so the RPC
-- functions below have something to point at.

create table if not exists public.discharge_requests (
  request_id int8 generated by default as identity primary key,
  patient_id int8 not null references public.patients (id),
  requested_by int8 not null references public.officers (officer_id),
  status text not null default 'Pending',
  billing_verified bool not null default false,
  "timestamp" timestamptz not null default now()
);

alter table public.discharge_requests enable row level security;
-- No RLS policies on purpose — same lockdown as officers/credentials/patients.
-- The only access path is the SECURITY DEFINER functions below.

create table if not exists public.tasks (
  task_id int8 generated by default as identity primary key,
  assigned_to int8 not null references public.officers (officer_id),
  discharge_id int8 not null references public.discharge_requests (request_id),
  task_type text not null,
  status text not null default 'Pending'
);

alter table public.tasks enable row level security;

-- ── patients ────────────────────────────────────────────────────────────
-- Every patients column except id (identity) and created_at (default now())
-- is settable by the nurse. CREATE OR REPLACE can't change a function's
-- return/param types in place, so old signatures are dropped first.

alter table public.patients rename column philhealth_status to philhealth_no;

drop function if exists create_patient(text, date, text, int8, date);
drop function if exists create_patient(text, date, text, int8, timestamptz);
drop function if exists create_patient(text, date, text, int8, int8, date, text, text, int8, timestamptz);
drop function if exists update_patient(int8, text, date, text, date, int8);
drop function if exists update_patient(int8, text, date, text, timestamptz, int8);
drop function if exists update_patient(int8, text, date, text, int8, date, text, text, int8, timestamptz, int8);
drop function if exists list_patients_by_officer(int8);

create or replace function create_patient(
  p_full_name text,
  p_admission_date date,
  p_philhealth_no text,
  p_officer_id int8,
  p_age int8 default null,
  p_date_of_birth date default null,
  p_contact_number text default null,
  p_emergency_contact text default null,
  p_room_number int8 default null,
  p_discharge_date timestamptz default null
)
returns table (
  id int8,
  full_name text,
  admission_date date,
  philhealth_no text,
  officer_id int8,
  age int8,
  date_of_birth date,
  contact_number text,
  emergency_contact text,
  room_number int8,
  discharge_date timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  insert into patients (
    full_name, admission_date, philhealth_no, officer_id,
    age, date_of_birth, contact_number, emergency_contact, room_number, discharge_date
  )
  values (
    p_full_name, p_admission_date, p_philhealth_no, p_officer_id,
    p_age, p_date_of_birth, p_contact_number, p_emergency_contact, p_room_number, p_discharge_date
  )
  returning
    patients.id, patients.full_name, patients.admission_date, patients.philhealth_no, patients.officer_id,
    patients.age, patients.date_of_birth, patients.contact_number, patients.emergency_contact, patients.room_number, patients.discharge_date;
end;
$$;

create or replace function update_patient(
  p_id int8,
  p_full_name text,
  p_admission_date date,
  p_philhealth_no text,
  p_age int8,
  p_date_of_birth date,
  p_contact_number text,
  p_emergency_contact text,
  p_room_number int8,
  p_discharge_date timestamptz,
  p_officer_id int8
)
returns table (
  id int8,
  full_name text,
  admission_date date,
  philhealth_no text,
  officer_id int8,
  age int8,
  date_of_birth date,
  contact_number text,
  emergency_contact text,
  room_number int8,
  discharge_date timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  update patients
  set full_name = p_full_name,
      admission_date = p_admission_date,
      philhealth_no = p_philhealth_no,
      age = p_age,
      date_of_birth = p_date_of_birth,
      contact_number = p_contact_number,
      emergency_contact = p_emergency_contact,
      room_number = p_room_number,
      discharge_date = p_discharge_date
  where patients.id = p_id
    and patients.officer_id = p_officer_id
  returning
    patients.id, patients.full_name, patients.admission_date, patients.philhealth_no, patients.officer_id,
    patients.age, patients.date_of_birth, patients.contact_number, patients.emergency_contact, patients.room_number, patients.discharge_date;
end;
$$;

create or replace function list_patients_by_officer(p_officer_id int8)
returns table (
  id int8,
  full_name text,
  admission_date date,
  philhealth_no text,
  officer_id int8,
  age int8,
  date_of_birth date,
  contact_number text,
  emergency_contact text,
  room_number int8,
  discharge_date timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  select
    patients.id, patients.full_name, patients.admission_date, patients.philhealth_no, patients.officer_id,
    patients.age, patients.date_of_birth, patients.contact_number, patients.emergency_contact, patients.room_number, patients.discharge_date
  from patients
  where patients.officer_id = p_officer_id
  order by patients.admission_date desc;
end;
$$;

-- ── discharge_requests ─────────────────────────────────────────────────

create or replace function create_discharge_request(
  p_patient_id int8,
  p_requested_by int8
)
returns table (
  request_id int8,
  patient_id int8,
  requested_by int8,
  status text,
  billing_verified bool,
  "timestamp" timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  insert into discharge_requests (patient_id, requested_by, status, billing_verified, "timestamp")
  values (p_patient_id, p_requested_by, 'Pending', false, now())
  returning discharge_requests.request_id, discharge_requests.patient_id, discharge_requests.requested_by, discharge_requests.status, discharge_requests.billing_verified, discharge_requests."timestamp";
end;
$$;

-- Status update is scoped to the officer who created the request — a nurse
-- can only change the status of discharge requests they themselves filed.
create or replace function update_discharge_request_status(
  p_request_id int8,
  p_status text,
  p_requested_by int8
)
returns table (
  request_id int8,
  patient_id int8,
  requested_by int8,
  status text,
  billing_verified bool,
  "timestamp" timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  update discharge_requests
  set status = p_status
  where discharge_requests.request_id = p_request_id
    and discharge_requests.requested_by = p_requested_by
  returning discharge_requests.request_id, discharge_requests.patient_id, discharge_requests.requested_by, discharge_requests.status, discharge_requests.billing_verified, discharge_requests."timestamp";
end;
$$;

create or replace function list_discharge_requests_by_officer(p_officer_id int8)
returns table (
  request_id int8,
  patient_id int8,
  patient_name text,
  status text,
  billing_verified bool,
  "timestamp" timestamptz
)
language plpgsql
security definer
as $$
begin
  return query
  select dr.request_id, dr.patient_id, p.full_name, dr.status, dr.billing_verified, dr."timestamp"
  from discharge_requests dr
  join patients p on p.id = dr.patient_id
  where dr.requested_by = p_officer_id
  order by dr."timestamp" desc;
end;
$$;

-- ── tasks ──────────────────────────────────────────────────────────────

create or replace function list_tasks_by_officer(p_officer_id int8)
returns table (
  task_id int8,
  discharge_id int8,
  patient_name text,
  task_type text,
  status text
)
language plpgsql
security definer
as $$
begin
  return query
  select t.task_id, t.discharge_id, p.full_name, t.task_type, t.status
  from tasks t
  join discharge_requests dr on dr.request_id = t.discharge_id
  join patients p on p.id = dr.patient_id
  where t.assigned_to = p_officer_id
  order by t.task_id desc;
end;
$$;

-- Status update is scoped to the assigned officer only.
create or replace function update_task_status(
  p_task_id int8,
  p_status text,
  p_officer_id int8
)
returns table (
  task_id int8,
  discharge_id int8,
  task_type text,
  status text
)
language plpgsql
security definer
as $$
begin
  return query
  update tasks
  set status = p_status
  where tasks.task_id = p_task_id
    and tasks.assigned_to = p_officer_id
  returning tasks.task_id, tasks.discharge_id, tasks.task_type, tasks.status;
end;
$$;

-- ── grants ─────────────────────────────────────────────────────────────

revoke all on function create_patient(text, date, text, int8, int8, date, text, text, int8, timestamptz) from public;
revoke all on function update_patient(int8, text, date, text, int8, date, text, text, int8, timestamptz, int8) from public;
revoke all on function list_patients_by_officer(int8) from public;
revoke all on function create_discharge_request(int8, int8) from public;
revoke all on function update_discharge_request_status(int8, text, int8) from public;
revoke all on function list_discharge_requests_by_officer(int8) from public;
revoke all on function list_tasks_by_officer(int8) from public;
revoke all on function update_task_status(int8, text, int8) from public;

grant execute on function create_patient(text, date, text, int8, int8, date, text, text, int8, timestamptz) to anon;
grant execute on function update_patient(int8, text, date, text, int8, date, text, text, int8, timestamptz, int8) to anon;
grant execute on function list_patients_by_officer(int8) to anon;
grant execute on function create_discharge_request(int8, int8) to anon;
grant execute on function update_discharge_request_status(int8, text, int8) to anon;
grant execute on function list_discharge_requests_by_officer(int8) to anon;
grant execute on function list_tasks_by_officer(int8) to anon;
grant execute on function update_task_status(int8, text, int8) to anon;
